// export const categories = [
//     { name: 'New', class: "fi-xnsuxl-star-solid"},
//     { name: 'Coding', class: "fi-xnsuxl-code-solid" },
//     { name: 'ReactJS', class: "fi-xnsuxl-replit-old" },
//     { name: 'Music', class: "fi-xnsuxl-music-solid" },
//     { name: 'DRG', class: "fi-snslxl-minecraft-pickaxe" },
//     { name: 'Education', class: "fi-xtsuxl-graduation-cap-solid" },
//     { name: 'Podcast', class: "fi-xnsuxl-microphone-solid" },
//     { name: 'Anime', class: "fi-ctsuxl-robot" },
//     { name: 'Movie', class: "fi-xnsuxl-videocamera-solid" },
//     { name: 'Gaming', class: "fi-xnsuxl-gamepad-solid" },
//     { name: 'Live', class: "fi-xnsuxl-tv-vintage-solid"  },
//     { name: 'Sport', class: "fi-cnluxl-small" },
//     { name: 'Fashion', class: "fi-cnsuxl-user-tie-circle" },
//   ];

  export const categories = [
    { name: 'search', src:     "./assets/star.png" },
    { name: 'New', src:        "./assets/star.png" },
    { name: 'Coding', src:     "./assets/code.png" },
    { name: 'ReactJS', src:    "./assets/brand-react.png" },
    { name: 'Music', src:      "./assets/music.png" },
    { name: 'DRG', src:        "./assets/pick.png" },
    { name: 'Education', src:  "./assets/education.png"},
    { name: 'Podcast', src:    "./assets/podcast.png" },
    { name: 'Anime', src:      "./assets/anime.png" },
    { name: 'Movie', src:      "./assets/movies.png" },
    { name: 'Gaming', src:     "./assets/gaming.png" },
    { name: 'Live', src:       "./assets/live.png" },
    { name: 'Sport', src:      "./assets/sports.png" },
    { name: 'Fashion', src:    "./assets/fashio.png" },
  ];