// export const categories = [
//     { name: 'New', class: "fi-xnsuxl-star-solid"},
//     { name: 'Coding', class: "fi-xnsuxl-code-solid" },
//     { name: 'ReactJS', class: "fi-xnsuxl-replit-old" },
//     { name: 'Music', class: "fi-xnsuxl-music-solid" },
//     { name: 'DRG', class: "fi-snslxl-minecraft-pickaxe" },
//     { name: 'Education', class: "fi-xtsuxl-graduation-cap-solid" },
//     { name: 'Podcast', class: "fi-xnsuxl-microphone-solid" },
//     { name: 'Anime', class: "fi-ctsuxl-robot" },
//     { name: 'Movie', class: "fi-xnsuxl-videocamera-solid" },
//     { name: 'Gaming', class: "fi-xnsuxl-gamepad-solid" },
//     { name: 'Live', class: "fi-xnsuxl-tv-vintage-solid"  },
//     { name: 'Sport', class: "fi-cnluxl-small" },
//     { name: 'Fashion', class: "fi-cnsuxl-user-tie-circle" },
//   ];

  export const categories = [
    { name: 'search', src:     "/src/assets/star.png" },
    { name: 'New', src:        "/src/assets/star.png" },
    { name: 'Coding', src:     "/src/assets/code.png" },
    { name: 'ReactJS', src:    "/src/assets/brand-react.png" },
    { name: 'Music', src:      "/src/assets/music.png" },
    { name: 'DRG', src:        "/src/assets/pick.png" },
    { name: 'Education', src:  "/src/assets/education.png"},
    { name: 'Podcast', src:    "/src/assets/podcast.png" },
    { name: 'Anime', src:      "/src/assets/anime.png" },
    { name: 'Movie', src:      "/src/assets/movies.png" },
    { name: 'Gaming', src:     "/src/assets/gaming.png" },
    { name: 'Live', src:       "/src/assets/live.png" },
    { name: 'Sport', src:      "/src/assets/sports.png" },
    { name: 'Fashion', src:    "/src/assets/fashio.png" },
  ];